title: Hello, world! I'm Mohil Patel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mohil Patel # add your name
author-img: photo.png # add your photo
about-author: ML and DL Enthusiast <br> Software Development <br> Graphic Designing # add description
social-twitter: mohilpatel25 # add your Twitter handle
social-facebook: mohil.patel.5855 # add your Facebook handle
social-github: mohilpatel25 # add your Github handle
social-linkedin: mohilpatel25 # add your Linkedin handle
social-email: mohilpatel21@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
